# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('value', models.IntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Metrics')),
            ],
        ),
        migrations.AddField(
            model_name='entries',
            name='daydate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
